export default InputsCompany = [
    {
        'title':'Numero de Ruc',
        'value':'',
        'instruction':'',
        'required':true,
        'type':'input',
        'value':'',
        'values':[   
                    {
                        'label':'Persona',
                        'value':'Persona',
                        'id':1
                    },
                    {
                        'label':'Empresa',
                        'value':'Empresa',
                        'id':2
                    }
                ],
        'id':1,
        'erroMessage':'',
        'ruc':'',
        'key':'ruc',
        'inputType':'number-pad',
        'maxLimit':20
    },
    {
        'title':'Razon Social',
        'instruction':'',
        'required':true,
        'type':'input',
        'value':'',
        'values':[
                ],
        'id':2,
        'user_id_type':'',
        'name':'',
        'key':'name',
        'erroMessage':'',

    },
    {
        'title':'DATOS DEL REPRESENTANTE LEGAL',
        'type':'Text',
        'id':3,
        'erroMessage':'',
    },
    {
        'title':'Tipo de Identification',
        'value':'',
        'instruction':'',
        'popupText':'popup text',
        'required':false,
        'legalrep_id_type':'',
        'key':'legalrep_id_type',
        'type':'select',
        'id':4,
        'erroMessage':'',
        'values':[   
            {
                'label':'DNI',
                'value':'DNI',
                'id':1
            },
            {
                'label':'CE',
                'value':'CE',
                'id':2
            },
            {
                'label':'PASAPORTE',
                'value':'PASAPORTE',
                'id':3
            }
        ],
    },
    {
        'title':'Número de Identificación',
        'value':'',
        'legalrep_number':'',
        'key':'legalrep_number',
        'instruction':'',
        'required':true,
        'type':'input',
        'id':5,
        'erroMessage':'',

    },
    {
        // 'title':'Nombre del Representante Legal',
        'title':'Nombre',
        'value':'',
        'legalrep_name':'',
        'key':'legalrep_name',
        'instruction':'',
        'required':true,
        'type':'input',
        'id':6,
        'erroMessage':'',
    },
    {
        'title':'DATOS OPCIONALES',
        'subtitle':'Si no los tiene a la mano, descuide, déjelos en blanco y nosotros le ayudamos a completarlos.',
        'type':'Text',
        'id':3,
        'erroMessage':'',
    },
    {
        'title':'Dirección',
        'value':'',
        'address':'',
        'key':'address',
        'instruction':'',
        'required':false,
        'type':'input',
        'id':9,
        'erroMessage':'',
    },
    {
        'title':'Distrito',
        'value':'',
        'district':'',
        'key':'district',
        'instruction':'',
        'required':false,
        'type':'input',
        'id':10,
        'erroMessage':'',
    },
    {
        'title':'Provincia',
        'value':'',
        'instruction':'',
        'province':'',
        'key':'province',
        'required':false,
        'type':'input',
        'id':11,
        'erroMessage':'',
    },
    {
        'title':'Departamento',
        'value':'',
        'key':'department',
        'department':'',
        'instruction':'',
        'required':false,
        'type':'input',
        'id':12,
        'erroMessage':'',
    },
    {
        'title':'País',
        'value':'',
        'instruction':'',
        'required':false,
        'country':'',
        'key':'country',
        'type':'input',
        'id':13
    },
    {
        'title':'Actividad Comercial',
        'value':'',
        'instruction':'* comercio, educación, consultoría, etc.',
        'required':false,
        'activity':'',
        'key':'activity',
        'type':'input',
        'id':14
    },
    {
        'title':'Fecha de Fundación',
        'value':'',
        'instruction':'',
        'required':false,
        'established':'',
        'key':'established',
        'type':'date',
        'id':15
    }
]